version: '3.8'
services:
  node-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mycar-api
    command: yarn start:dev
    ports:
      - '${APP_PORT}:1102'
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    networks:
      - backend
networks:
  backend:
